// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Coffee nodes documents
 */
interface CoffeeNodesDocumentData {
  /**
   * Name field in *Coffee nodes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coffee_nodes.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * node type field in *Coffee nodes*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: coffee_nodes.node_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  node_type: prismic.ContentRelationshipField;
}

/**
 * Coffee nodes document from Prismic
 *
 * - **API ID**: `coffee_nodes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoffeeNodesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CoffeeNodesDocumentData>,
    "coffee_nodes",
    Lang
  >;

type HomeDocumentDataSlicesSlice = FeatureSlice | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Node types documents
 */
interface NodeTypesDocumentData {
  /**
   * name field in *Node types*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: node_types.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Node types document from Prismic
 *
 * - **API ID**: `node_types`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NodeTypesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NodeTypesDocumentData>,
    "node_types",
    Lang
  >;

export type AllDocumentTypes =
  | CoffeeNodesDocument
  | HomeDocument
  | NodeTypesDocument;

/**
 * Primary content in *Features → Primary*
 */
export interface FeatureSliceDefaultPrimary {
  /**
   * Coffee bar image field in *Features → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.coffe_bar_feature_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  coffe_bar_feature_image: prismic.ImageField<never>;

  /**
   * Coffee bar headline field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.coffee_bar_headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coffee_bar_headline: prismic.KeyTextField;

  /**
   * Coffee bar description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.coffee_bar_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  coffee_bar_description: prismic.RichTextField;

  /**
   * Coffee bar Link field in *Features → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.coffee_bar_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  coffee_bar_link: prismic.LinkField;

  /**
   * Coffee bar link text field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.coffee_bar_link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coffee_bar_link_text: prismic.KeyTextField;

  /**
   * Subscription image field in *Features → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.subscription_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  subscription_image: prismic.ImageField<never>;

  /**
   * Subscription headline field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.subscription_headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscription_headline: prismic.KeyTextField;

  /**
   * Subscription description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.subscription_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subscription_description: prismic.RichTextField;

  /**
   * Subscription link field in *Features → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.subscription_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subscription_link: prismic.LinkField;

  /**
   * Subscription link text field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.subscription_link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscription_link_text: prismic.KeyTextField;

  /**
   * App headline field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.app_headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  app_headline: prismic.KeyTextField;

  /**
   * App image field in *Features → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.app_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  app_image: prismic.ImageField<never>;

  /**
   * App description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.app_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  app_description: prismic.RichTextField;

  /**
   * App link field in *Features → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.app_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  app_link: prismic.LinkField;

  /**
   * App link text field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.primary.app_link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  app_link_text: prismic.KeyTextField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeatureSliceVariation = FeatureSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSlice = prismic.SharedSlice<
  "feature",
  FeatureSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Coffee nodes field in *Hero → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].coffee_nodes
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  coffee_nodes: prismic.ContentRelationshipField<"coffee_nodes">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CoffeeNodesDocument,
      CoffeeNodesDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NodeTypesDocument,
      NodeTypesDocumentData,
      AllDocumentTypes,
      FeatureSlice,
      FeatureSliceDefaultPrimary,
      FeatureSliceVariation,
      FeatureSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
    };
  }
}
